package com.example.demo10.raffles.hotelmgmt; // Your package

// No PasswordUtil import is needed as we are storing plain text passwords.

import javafx.application.Platform; // For showing critical error alerts
import javafx.scene.control.Alert;
import javafx.scene.control.ButtonType;

import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.HashMap;
import java.util.Map;

import com.example.demo10.raffles.hotelmgmt.dao.RoomTypeDAO;
import com.example.demo10.raffles.hotelmgmt.model.RoomType;
import javafx.collections.ObservableList;
import java.math.BigDecimal;

public class DatabaseInitializer {

    public static void initialize() {
        try (Connection conn = DatabaseConnector.getConnection(); // Uses your DatabaseConnector
             Statement stmt = conn.createStatement()) {

            System.out.println("Initializing database schema (HSQLDB)...");

            // Role Table
            stmt.execute("CREATE TABLE IF NOT EXISTS Role (" +
                    "RoleID INTEGER GENERATED BY DEFAULT AS IDENTITY(START WITH 1, INCREMENT BY 1) PRIMARY KEY, " +
                    "RoleName VARCHAR(50) NOT NULL UNIQUE, " +
                    "Description VARCHAR(1000), " +
                    "Permissions VARCHAR(4000))");
            System.out.println("Checked/Created Role table.");

            // Department Table
            stmt.execute("CREATE TABLE IF NOT EXISTS Department (" +
                    "DepartmentID INTEGER GENERATED BY DEFAULT AS IDENTITY(START WITH 1, INCREMENT BY 1) PRIMARY KEY, " +
                    "DepartmentName VARCHAR(100) NOT NULL UNIQUE)");
            System.out.println("Checked/Created Department table.");

            // Employee Table - Storing plain text password
            stmt.execute("CREATE TABLE IF NOT EXISTS Employee (" +
                    "EmployeeID INTEGER GENERATED BY DEFAULT AS IDENTITY(START WITH 1, INCREMENT BY 1) PRIMARY KEY, " +
                    "FirstName VARCHAR(50), LastName VARCHAR(50), RoleID INTEGER, DepartmentID INTEGER, " +
                    "Username VARCHAR(50) NOT NULL UNIQUE, Password VARCHAR(255) NOT NULL, " + // Plain text Password
                    "ContactNumber VARCHAR(20), Email VARCHAR(100) UNIQUE, HireDate DATE, IsActive BOOLEAN DEFAULT TRUE, " +
                    "FOREIGN KEY (RoleID) REFERENCES Role(RoleID) ON DELETE SET NULL, " +
                    "FOREIGN KEY (DepartmentID) REFERENCES Department(DepartmentID) ON DELETE SET NULL)");
            System.out.println("Checked/Created Employee table.");

            // Guest Table
            stmt.execute("CREATE TABLE IF NOT EXISTS Guest (" +
                    "GuestID INTEGER GENERATED BY DEFAULT AS IDENTITY(START WITH 1, INCREMENT BY 1) PRIMARY KEY, " +
                    "FirstName VARCHAR(50), LastName VARCHAR(50), Email VARCHAR(100), PhoneNumber VARCHAR(20), " +
                    "Address VARCHAR(255), Nationality VARCHAR(50), DateOfBirth DATE, " +
                    "IdentificationType VARCHAR(50), IdentificationNumber VARCHAR(50), " +
                    "LoyaltyProgramID VARCHAR(50), Preferences CLOB, Notes CLOB)");
            System.out.println("Checked/Created Guest table.");

            // RoomType Table
            stmt.execute("CREATE TABLE IF NOT EXISTS RoomType (" +
                    "RoomTypeID INTEGER GENERATED BY DEFAULT AS IDENTITY(START WITH 1, INCREMENT BY 1) PRIMARY KEY, " +
                    "TypeName VARCHAR(50) NOT NULL, " +
                    "Description CLOB, BaseRate DECIMAL(10,2), DefaultMaxOccupancy INTEGER, IncludedAmenities CLOB)");
            System.out.println("Checked/Created RoomType table.");

            // Room Table
            stmt.execute("CREATE TABLE IF NOT EXISTS Room (" +
                    "RoomID INTEGER GENERATED BY DEFAULT AS IDENTITY(START WITH 1, INCREMENT BY 1) PRIMARY KEY, " +
                    "RoomNumber VARCHAR(10) NOT NULL UNIQUE, RoomTypeID INTEGER, FloorNumber INTEGER, " +
                    "Status VARCHAR(50) DEFAULT 'Available', Features CLOB, MaxOccupancy INTEGER, IsSmoking BOOLEAN DEFAULT FALSE, Notes CLOB, " +
                    "FOREIGN KEY (RoomTypeID) REFERENCES RoomType(RoomTypeID) ON DELETE SET NULL)");
            System.out.println("Checked/Created Room table.");

            // Reservation Table
            stmt.execute("CREATE TABLE IF NOT EXISTS Reservation (" +
                    "ReservationID INTEGER GENERATED BY DEFAULT AS IDENTITY(START WITH 1, INCREMENT BY 1) PRIMARY KEY, " +
                    "GuestID INTEGER, RoomID INTEGER, RoomTypeID INTEGER, " +
                    "CheckInDate DATE NOT NULL, CheckOutDate DATE NOT NULL, NumberOfAdults INTEGER, NumberOfChildren INTEGER, " +
                    "Status VARCHAR(50) DEFAULT 'Pending', BookingSource VARCHAR(50), TotalEstimatedCost DECIMAL(10,2), " +
                    "DateBooked DATE DEFAULT CURRENT_DATE, SpecialRequests CLOB, Notes CLOB, " +
                    "FOREIGN KEY (GuestID) REFERENCES Guest(GuestID) ON DELETE CASCADE, " +
                    "FOREIGN KEY (RoomID) REFERENCES Room(RoomID) ON DELETE SET NULL, " +
                    "FOREIGN KEY (RoomTypeID) REFERENCES RoomType(RoomTypeID) ON DELETE SET NULL)");
            System.out.println("Checked/Created Reservation table.");

            // Invoice Table
            stmt.execute("DROP TABLE IF EXISTS Charge");
            stmt.execute("DROP TABLE IF EXISTS Payment");
            stmt.execute("DROP TABLE IF EXISTS Invoice");
            
            stmt.execute("CREATE TABLE IF NOT EXISTS Invoice (" +
                    "InvoiceID INTEGER GENERATED BY DEFAULT AS IDENTITY(START WITH 1, INCREMENT BY 1) PRIMARY KEY, " +
                    "ReservationID INTEGER, GuestID INTEGER, InvoiceDate DATE DEFAULT CURRENT_DATE, DueDate DATE, " +
                    "TotalAmount DECIMAL(10,2) DEFAULT 0.00, AmountPaid DECIMAL(10,2) DEFAULT 0.00, " +
                    "BalanceDue DECIMAL(10,2) DEFAULT 0.00, " +
                    "Status VARCHAR(50) DEFAULT 'Unpaid', " +
                    "FOREIGN KEY (ReservationID) REFERENCES Reservation(ReservationID) ON DELETE SET NULL, " +
                    "FOREIGN KEY (GuestID) REFERENCES Guest(GuestID) ON DELETE SET NULL)");
            System.out.println("Recreated Invoice table with corrected structure.");

            // Service Table
            stmt.execute("CREATE TABLE IF NOT EXISTS Service (" +
                    "ServiceID INTEGER GENERATED BY DEFAULT AS IDENTITY(START WITH 1, INCREMENT BY 1) PRIMARY KEY, " +
                    "ServiceName VARCHAR(100) NOT NULL UNIQUE, Description CLOB, DefaultPrice DECIMAL(10,2), DepartmentID INTEGER, " +
                    "FOREIGN KEY (DepartmentID) REFERENCES Department(DepartmentID) ON DELETE SET NULL)");
            System.out.println("Checked/Created Service table.");

            // Charge Table
            stmt.execute("CREATE TABLE IF NOT EXISTS Charge (" +
                    "ChargeID INTEGER GENERATED BY DEFAULT AS IDENTITY(START WITH 1, INCREMENT BY 1) PRIMARY KEY, " +
                    "InvoiceID INTEGER NOT NULL, ServiceID INTEGER, Description VARCHAR(255), Amount DECIMAL(10,2) NOT NULL, " +
                    "ChargeDate DATE DEFAULT CURRENT_DATE, ChargedByEmployeeID INTEGER, " +
                    "FOREIGN KEY (InvoiceID) REFERENCES Invoice(InvoiceID) ON DELETE CASCADE, " +
                    "FOREIGN KEY (ServiceID) REFERENCES Service(ServiceID) ON DELETE SET NULL, " +
                    "FOREIGN KEY (ChargedByEmployeeID) REFERENCES Employee(EmployeeID) ON DELETE SET NULL)");
            System.out.println("Recreated Charge table with corrected structure.");

            // Payment Table
            stmt.execute("CREATE TABLE IF NOT EXISTS Payment (" +
                    "PaymentID INTEGER GENERATED BY DEFAULT AS IDENTITY(START WITH 1, INCREMENT BY 1) PRIMARY KEY, " +
                    "InvoiceID INTEGER NOT NULL, PaymentDate DATE DEFAULT CURRENT_DATE, AmountPaid DECIMAL(10,2) NOT NULL, " +
                    "PaymentMethod VARCHAR(50), TransactionReference VARCHAR(100), ProcessedByEmployeeID INTEGER, " +
                    "FOREIGN KEY (InvoiceID) REFERENCES Invoice(InvoiceID) ON DELETE CASCADE, " +
                    "FOREIGN KEY (ProcessedByEmployeeID) REFERENCES Employee(EmployeeID) ON DELETE SET NULL)");
            System.out.println("Checked/Created Payment table.");

            // GuestAccount Table for self-service portal
            stmt.execute("CREATE TABLE IF NOT EXISTS GuestAccount (" +
                    "AccountID INTEGER GENERATED BY DEFAULT AS IDENTITY(START WITH 1, INCREMENT BY 1) PRIMARY KEY, " +
                    "Email VARCHAR(100) NOT NULL UNIQUE, " +
                    "Password VARCHAR(255) NOT NULL, " +
                    "GuestID INTEGER NOT NULL, " +
                    "IsActive BOOLEAN DEFAULT TRUE, " +
                    "VerificationCode VARCHAR(50), " +
                    "IsVerified BOOLEAN DEFAULT FALSE, " +
                    "LastLogin TIMESTAMP, " +
                    "CreatedAt TIMESTAMP DEFAULT CURRENT_TIMESTAMP, " +
                    "FOREIGN KEY (GuestID) REFERENCES Guest(GuestID) ON DELETE CASCADE)");
            System.out.println("Checked/Created GuestAccount table.");

            // HousekeepingTask Table
            stmt.execute("CREATE TABLE IF NOT EXISTS HousekeepingTask (" +
                    "TaskID INTEGER GENERATED BY DEFAULT AS IDENTITY(START WITH 1, INCREMENT BY 1) PRIMARY KEY, " +
                    "RoomID INTEGER NOT NULL, AssignedEmployeeID INTEGER, TaskType VARCHAR(100), ScheduledDate DATE, " +
                    "Status VARCHAR(50) DEFAULT 'Pending', CompletionTime TIMESTAMP, Notes CLOB, " +
                    "FOREIGN KEY (RoomID) REFERENCES Room(RoomID) ON DELETE CASCADE, " +
                    "FOREIGN KEY (AssignedEmployeeID) REFERENCES Employee(EmployeeID) ON DELETE SET NULL)");
            System.out.println("Checked/Created HousekeepingTask table.");

            // MaintenanceRequest Table
            stmt.execute("CREATE TABLE IF NOT EXISTS MaintenanceRequest (" +
                    "RequestID INTEGER GENERATED BY DEFAULT AS IDENTITY(START WITH 1, INCREMENT BY 1) PRIMARY KEY, " +
                    "RoomID INTEGER, ReportedByGuestID INTEGER, ReportedByEmployeeID INTEGER, " +
                    "ReportedDate DATE DEFAULT CURRENT_DATE, IssueDescription CLOB NOT NULL, Priority VARCHAR(50) DEFAULT 'Medium', Status VARCHAR(50) DEFAULT 'Open', " +
                    "FOREIGN KEY (RoomID) REFERENCES Room(RoomID) ON DELETE SET NULL, " +
                    "FOREIGN KEY (ReportedByGuestID) REFERENCES Guest(GuestID) ON DELETE SET NULL, " +
                    "FOREIGN KEY (ReportedByEmployeeID) REFERENCES Employee(EmployeeID) ON DELETE SET NULL)");
            System.out.println("Checked/Created MaintenanceRequest table.");

            System.out.println("All tables checked/created successfully.");

            // Insert default data (roles, departments, admin user)
            insertDefaultRolesAndDepartments(stmt);
            insertDefaultAdminUser(stmt); // This will now store a plain text password

            System.out.println("Default data checked/inserted.");
            
            // Ensure room types exist
            ensureRoomTypesExist();
            
            // Initialize room data
            initializeRoomData();
            
            // Ensure services exist
            ensureServicesExist();
            
            System.out.println("Database initialization complete.");

        } catch (SQLException e) {
            System.err.println("DATABASE INITIALIZATION CRITICAL ERROR: " + e.getMessage());
            e.printStackTrace();
            // This is a critical failure, inform the user and potentially exit.
            // Ensure this runs on the JavaFX Application Thread if called from MainApp.start() context
            if (Platform.isFxApplicationThread()) {
                showCriticalErrorAlert(e);
            } else {
                Platform.runLater(() -> showCriticalErrorAlert(e));
            }
        }
    }

    private static void showCriticalErrorAlert(SQLException e) {
        Alert alert = new Alert(Alert.AlertType.ERROR);
        alert.setTitle("Database Initialization Error");
        alert.setHeaderText("A critical error occurred while setting up the database.");
        alert.setContentText("The application cannot continue. Please check the console logs for details.\nError: " + e.getMessage());
        alert.showAndWait();
        Platform.exit(); // Exit the JavaFX application
    }


    private static void insertDefaultRolesAndDepartments(Statement stmt) throws SQLException {
        insertRoleIfNotExists(stmt, "Admin", "Full system administrator.", "ALL_PERMISSIONS");
        insertRoleIfNotExists(stmt, "Staff", "Front desk and operational staff.", "GUEST_VIEW,GUEST_EDIT,BOOKING_VIEW,BOOKING_EDIT");
        insertRoleIfNotExists(stmt, "Housekeeper", "Housekeeping staff.", "HOUSEKEEPING_VIEW,HOUSEKEEPING_UPDATE");

        insertDepartmentIfNotExists(stmt, "Management");
        insertDepartmentIfNotExists(stmt, "Front Office");
        insertDepartmentIfNotExists(stmt, "Housekeeping");
        insertDepartmentIfNotExists(stmt, "Maintenance");
        insertDepartmentIfNotExists(stmt, "Food & Beverage");
        insertDepartmentIfNotExists(stmt, "Security");
    }

    private static void insertRoleIfNotExists(Statement stmt, String roleName, String description, String permissions) throws SQLException {
        // Use PreparedStatement for safety against SQL injection, though less critical for hardcoded values
        String checkSql = "SELECT COUNT(*) FROM Role WHERE RoleName = ?";
        boolean exists = false;
        try (PreparedStatement checkPstmt = stmt.getConnection().prepareStatement(checkSql)) {
            checkPstmt.setString(1, roleName);
            try (ResultSet rs = checkPstmt.executeQuery()) {
                if (rs.next() && rs.getInt(1) > 0) {
                    exists = true;
                }
            }
        }

        if (!exists) {
            String insertSql = "INSERT INTO Role (RoleName, Description, Permissions) VALUES (?, ?, ?)";
            try (PreparedStatement insertPstmt = stmt.getConnection().prepareStatement(insertSql)) {
                insertPstmt.setString(1, roleName);
                insertPstmt.setString(2, description);
                insertPstmt.setString(3, permissions);
                insertPstmt.executeUpdate();
                System.out.println("Inserted default role: " + roleName);
            }
        }
    }

    private static void insertDepartmentIfNotExists(Statement stmt, String deptName) throws SQLException {
        String checkSql = "SELECT COUNT(*) FROM Department WHERE DepartmentName = ?";
        boolean exists = false;
        try (PreparedStatement checkPstmt = stmt.getConnection().prepareStatement(checkSql)) {
            checkPstmt.setString(1, deptName);
            try (ResultSet rs = checkPstmt.executeQuery()) {
                if (rs.next() && rs.getInt(1) > 0) {
                    exists = true;
                }
            }
        }

        if (!exists) {
            String insertSql = "INSERT INTO Department (DepartmentName) VALUES (?)";
            try (PreparedStatement insertPstmt = stmt.getConnection().prepareStatement(insertSql)) {
                insertPstmt.setString(1, deptName);
                insertPstmt.executeUpdate();
                System.out.println("Inserted default department: " + deptName);
            }
        }
    }

    private static void insertDefaultAdminUser(Statement stmt) throws SQLException {
        String checkSql = "SELECT COUNT(*) FROM Employee WHERE Username = 'admin'";
        boolean adminExists = false;
        try (PreparedStatement checkPstmt = stmt.getConnection().prepareStatement(checkSql)) {
            try (ResultSet rs = checkPstmt.executeQuery()) {
                if (rs.next() && rs.getInt(1) > 0) {
                    adminExists = true;
                }
            }
        }

        if (!adminExists) {
            int adminRoleId = getEntityIdByName(stmt, "Role", "RoleName", "Admin", "RoleID");
            int mgmtDeptId = getEntityIdByName(stmt, "Department", "DepartmentName", "Management", "DepartmentID");

            if (adminRoleId != -1 && mgmtDeptId != -1) {
                String adminPlainTextPassword = "admin123"; // PLAIN TEXT PASSWORD

                String insertSql = "INSERT INTO Employee (FirstName, LastName, Username, Password, Email, RoleID, DepartmentID, IsActive, HireDate) " +
                        "VALUES (?, ?, ?, ?, ?, ?, ?, TRUE, CURRENT_DATE)";
                try (PreparedStatement insertPstmt = stmt.getConnection().prepareStatement(insertSql)) {
                    insertPstmt.setString(1, "Default");
                    insertPstmt.setString(2, "Admin");
                    insertPstmt.setString(3, "admin");
                    insertPstmt.setString(4, adminPlainTextPassword); // Storing plain text
                    insertPstmt.setString(5, "admin@raffleshotel.com");
                    insertPstmt.setInt(6, adminRoleId);
                    insertPstmt.setInt(7, mgmtDeptId);
                    insertPstmt.executeUpdate();
                    System.out.println("Inserted default admin user (username: admin, password: admin123).");
                    System.out.println("WARNING: THIS IS A PLAIN TEXT PASSWORD. NOT SUITABLE FOR PRODUCTION.");
                }
            } else {
                System.err.println("Could not insert default admin: 'Admin' Role or 'Management' Department not found even after attempting to insert defaults. Check previous logs.");
            }
        }
    }

    // Helper to get ID for default role/department insertion, useful for setting up FKs
    private static int getEntityIdByName(Statement stmt, String tableName, String nameColumn, String nameValue, String idColumn) throws SQLException {
        // Using PreparedStatement within this helper for safety, even though called from a Statement context
        String sql = "SELECT " + idColumn + " FROM " + tableName + " WHERE " + nameColumn + " = ?";
        try (PreparedStatement pstmt = stmt.getConnection().prepareStatement(sql)) {
            pstmt.setString(1, nameValue);
            try (ResultSet rs = pstmt.executeQuery()) {
                if (rs.next()) {
                    return rs.getInt(idColumn);
                }
            }
        }
        return -1; // Indicates not found
    }

    /**
     * Initialize some sample room types and rooms for testing
     */
    private static void initializeRoomData() {
        System.out.println("Initializing room data...");
        
        try (Connection conn = DatabaseConnector.getConnection()) {
            // First check if tables exist and create them if needed
            createRoomTypesTable(conn);
            createRoomsTable(conn);
            
            // Debug: Check if RoomType table exists and has proper structure
            try {
                ResultSet tables = conn.getMetaData().getTables(null, null, "ROOMTYPE", null);
                System.out.println("RoomType table exists: " + tables.next());
            } catch (Exception e) {
                System.err.println("Error checking RoomType table: " + e.getMessage());
            }
            
            // Check if there are already room types
            PreparedStatement checkStmt = conn.prepareStatement("SELECT COUNT(*) FROM RoomType");
            ResultSet rs = checkStmt.executeQuery();
            int roomTypeCount = 0;
            if (rs.next()) {
                roomTypeCount = rs.getInt(1);
            }
            System.out.println("Current room type count: " + roomTypeCount);
            
            if (roomTypeCount == 0) {
                // Insert sample room types
                String[] typeInserts = {
                    "INSERT INTO RoomType (TypeName, Description, BaseRate, DefaultMaxOccupancy, IncludedAmenities) VALUES " +
                    "('Standard', 'Comfortable standard room with essential amenities.', 150.00, 2, 'Wi-Fi, TV, Mini Fridge')",
                    
                    "INSERT INTO RoomType (TypeName, Description, BaseRate, DefaultMaxOccupancy, IncludedAmenities) VALUES " +
                    "('Deluxe', 'Spacious deluxe room with premium amenities.', 250.00, 2, 'Wi-Fi, TV, Mini Bar, Bath Robes, Slippers')",
                    
                    "INSERT INTO RoomType (TypeName, Description, BaseRate, DefaultMaxOccupancy, IncludedAmenities) VALUES " +
                    "('Suite', 'Luxury suite with separate living area.', 350.00, 3, 'Wi-Fi, TV, Full Bar, Bath Robes, Slippers, Room Service')",
                    
                    "INSERT INTO RoomType (TypeName, Description, BaseRate, DefaultMaxOccupancy, IncludedAmenities) VALUES " +
                    "('Presidential', 'Ultimate luxury presidential suite with panoramic views.', 550.00, 4, 'Wi-Fi, Smart TV, Full Bar, Jacuzzi, Butler Service, VIP Access')"
                };
                
                int typesAdded = 0;
                for (String insert : typeInserts) {
                    try {
                        int rowsInserted = conn.createStatement().executeUpdate(insert);
                        typesAdded += rowsInserted;
                        System.out.println("Room type insert result: " + rowsInserted);
                    } catch (Exception e) {
                        System.err.println("Error inserting room type data: " + e.getMessage());
                    }
                }
                System.out.println("Sample room types initialized: " + typesAdded);
                
                // Verify room types were added
                checkStmt = conn.prepareStatement("SELECT COUNT(*) FROM RoomType");
                rs = checkStmt.executeQuery();
                if (rs.next()) {
                    System.out.println("Room types after insertion: " + rs.getInt(1));
                }
            }
            
            // Check if there are already rooms
            checkStmt = conn.prepareStatement("SELECT COUNT(*) FROM Room");
            rs = checkStmt.executeQuery();
            int roomCount = 0;
            if (rs.next()) {
                roomCount = rs.getInt(1);
            }
            System.out.println("Current room count: " + roomCount);
            
            if (roomCount == 0) {
                // Get room type IDs
                Map<String, Integer> roomTypeIds = new HashMap<>();
                rs = conn.createStatement().executeQuery("SELECT RoomTypeID, TypeName FROM RoomType");
                while (rs.next()) {
                    roomTypeIds.put(rs.getString("TypeName"), rs.getInt("RoomTypeID"));
                }
                
                System.out.println("Room type IDs found: " + roomTypeIds);
                
                // Insert sample rooms on different floors
                int roomsAdded = 0;
                
                // ... existing room creation code ...
                for (int floor = 1; floor <= 5; floor++) {
                    // Add rooms to each floor with various types
                    roomsAdded += addFloorRooms(conn, floor, roomTypeIds);
                }
                
                System.out.println("Total rooms created: " + roomsAdded);
                
                // Update a few rooms to different statuses
                String[] statusUpdates = {
                    "UPDATE Room SET Status = 'Occupied' WHERE RoomNumber IN ('101', '205', '302')",
                    "UPDATE Room SET Status = 'Reserved' WHERE RoomNumber IN ('103', '405', '506')",
                    "UPDATE Room SET Status = 'Maintenance' WHERE RoomNumber IN ('104', '308')",
                    "UPDATE Room SET Status = 'Cleaning' WHERE RoomNumber IN ('201', '402')"
                };
                
                int statusUpdatesApplied = 0;
                for (String update : statusUpdates) {
                    try {
                        int updated = conn.createStatement().executeUpdate(update);
                        statusUpdatesApplied += updated;
                    } catch (Exception e) {
                        System.err.println("Error updating room status: " + e.getMessage());
                    }
                }
                
                System.out.println("Room status updates applied: " + statusUpdatesApplied);
                
                // Final verification
                checkStmt = conn.prepareStatement("SELECT COUNT(*) FROM Room");
                rs = checkStmt.executeQuery();
                if (rs.next()) {
                    System.out.println("Final room count: " + rs.getInt(1));
                }
                
                System.out.println("Sample rooms initialized successfully.");
            } else {
                System.out.println("Rooms already exist in the database. Skipping room initialization.");
            }
        } catch (SQLException e) {
            System.err.println("Error initializing room data: " + e.getMessage());
            e.printStackTrace();
        }
    }
    
    /**
     * Helper method to add rooms to a specific floor
     */
    private static int addFloorRooms(Connection conn, int floor, Map<String, Integer> roomTypeIds) throws SQLException {
        int roomsAdded = 0;
        
        // Standard rooms (01-05)
        for (int roomNum = 1; roomNum <= 5; roomNum++) {
            String roomNumber = String.format("%d%02d", floor, roomNum);
            try {
                PreparedStatement stmt = conn.prepareStatement(
                    "INSERT INTO Room (RoomNumber, RoomTypeID, FloorNumber, Status, Features, MaxOccupancy, IsSmoking, Notes) VALUES (?, ?, ?, ?, ?, ?, ?, ?)"
                );
                stmt.setString(1, roomNumber);
                stmt.setInt(2, roomTypeIds.get("Standard"));
                stmt.setInt(3, floor);
                stmt.setString(4, "Available");
                stmt.setString(5, roomNum % 2 == 0 ? "Queen Bed" : "Twin Beds");
                stmt.setInt(6, 2);
                stmt.setBoolean(7, false);
                stmt.setString(8, "Standard room on floor " + floor);
                
                int result = stmt.executeUpdate();
                roomsAdded += result;
                System.out.println("Added standard room " + roomNumber + ": " + (result > 0 ? "Success" : "Failed"));
            } catch (Exception e) {
                System.err.println("Error inserting room " + roomNumber + ": " + e.getMessage());
            }
        }
        
        // Deluxe rooms (06-08)
        for (int roomNum = 6; roomNum <= 8; roomNum++) {
            String roomNumber = String.format("%d%02d", floor, roomNum);
            try {
                PreparedStatement stmt = conn.prepareStatement(
                    "INSERT INTO Room (RoomNumber, RoomTypeID, FloorNumber, Status, Features, MaxOccupancy, IsSmoking, Notes) VALUES (?, ?, ?, ?, ?, ?, ?, ?)"
                );
                stmt.setString(1, roomNumber);
                stmt.setInt(2, roomTypeIds.get("Deluxe"));
                stmt.setInt(3, floor);
                stmt.setString(4, "Available");
                stmt.setString(5, "King Bed, City View");
                stmt.setInt(6, 2);
                stmt.setBoolean(7, roomNum == 8);
                stmt.setString(8, "Deluxe room on floor " + floor);
                
                int result = stmt.executeUpdate();
                roomsAdded += result;
                System.out.println("Added deluxe room " + roomNumber + ": " + (result > 0 ? "Success" : "Failed"));
            } catch (Exception e) {
                System.err.println("Error inserting room " + roomNumber + ": " + e.getMessage());
            }
        }
        
        // Suite (09)
        String suiteNumber = String.format("%d%02d", floor, 9);
        try {
            PreparedStatement stmt = conn.prepareStatement(
                "INSERT INTO Room (RoomNumber, RoomTypeID, FloorNumber, Status, Features, MaxOccupancy, IsSmoking, Notes) VALUES (?, ?, ?, ?, ?, ?, ?, ?)"
            );
            stmt.setString(1, suiteNumber);
            stmt.setInt(2, roomTypeIds.get("Suite"));
            stmt.setInt(3, floor);
            stmt.setString(4, floor == 3 ? "Maintenance" : "Available");
            stmt.setString(5, "King Bed, Living Room, Ocean View");
            stmt.setInt(6, 3);
            stmt.setBoolean(7, false);
            stmt.setString(8, "Luxury suite on floor " + floor);
            
            int result = stmt.executeUpdate();
            roomsAdded += result;
            System.out.println("Added suite room " + suiteNumber + ": " + (result > 0 ? "Success" : "Failed"));
        } catch (Exception e) {
            System.err.println("Error inserting suite " + suiteNumber + ": " + e.getMessage());
        }
        
        // Add one presidential suite on top floor if this is the top floor
        if (floor == 5) {
            try {
                PreparedStatement stmt = conn.prepareStatement(
                    "INSERT INTO Room (RoomNumber, RoomTypeID, FloorNumber, Status, Features, MaxOccupancy, IsSmoking, Notes) VALUES (?, ?, ?, ?, ?, ?, ?, ?)"
                );
                stmt.setString(1, "510");
                stmt.setInt(2, roomTypeIds.get("Presidential"));
                stmt.setInt(3, 5);
                stmt.setString(4, "Available");
                stmt.setString(5, "Master Bedroom, Living Room, Dining Room, Private Terrace, Panoramic Views");
                stmt.setInt(6, 4);
                stmt.setBoolean(7, false);
                stmt.setString(8, "Our finest presidential suite on the top floor");
                
                int result = stmt.executeUpdate();
                roomsAdded += result;
                System.out.println("Added presidential suite: " + (result > 0 ? "Success" : "Failed"));
            } catch (Exception e) {
                System.err.println("Error inserting presidential suite: " + e.getMessage());
            }
        }
        
        return roomsAdded;
    }
    
    /**
     * Create the RoomType table if it doesn't exist
     */
    private static void createRoomTypesTable(Connection conn) throws SQLException {
        String createRoomTypeTable = 
            "CREATE TABLE IF NOT EXISTS RoomType (" +
            "RoomTypeID INTEGER IDENTITY PRIMARY KEY, " +
            "TypeName VARCHAR(50) NOT NULL, " +
            "Description CLOB, " +
            "BaseRate DECIMAL(10, 2) NOT NULL, " +
            "DefaultMaxOccupancy INTEGER NOT NULL DEFAULT 2, " +
            "IncludedAmenities CLOB" +
            ")";
        conn.createStatement().executeUpdate(createRoomTypeTable);
    }
    
    /**
     * Create the Room table if it doesn't exist
     */
    private static void createRoomsTable(Connection conn) throws SQLException {
        String createRoomTable = 
            "CREATE TABLE IF NOT EXISTS Room (" +
            "RoomID INTEGER IDENTITY PRIMARY KEY, " +
            "RoomNumber VARCHAR(10) NOT NULL UNIQUE, " +
            "RoomTypeID INTEGER, " +
            "FloorNumber INTEGER, " +
            "Status VARCHAR(20) DEFAULT 'Available', " +
            "Features CLOB, " +
            "MaxOccupancy INTEGER DEFAULT 2, " +
            "IsSmoking BIT DEFAULT 0, " +
            "Notes CLOB, " +
            "FOREIGN KEY (RoomTypeID) REFERENCES RoomType(RoomTypeID)" +
            ")";
        conn.createStatement().executeUpdate(createRoomTable);
    }

    /**
     * Ensures that the standard room types exist in the database.
     * This is crucial for proper room management functionality.
     */
    private static void ensureRoomTypesExist() {
        RoomTypeDAO roomTypeDAO = new RoomTypeDAO();
        ObservableList<RoomType> existingTypes = roomTypeDAO.getAllRoomTypes();
        
        // Only add default types if none exist
        if (existingTypes.isEmpty()) {
            System.out.println("No room types found. Adding default room types...");
            
            // Create Standard Room
            RoomType standard = new RoomType();
            standard.setTypeName("Standard");
            standard.setDescription("A comfortable standard room with essential amenities for a pleasant stay.");
            standard.setBaseRate(new BigDecimal("150.00"));
            standard.setDefaultMaxOccupancy(2);
            standard.setIncludedAmenities("Wi-Fi, TV, Mini-fridge, Coffee maker");
            roomTypeDAO.addRoomType(standard);
            
            // Create Deluxe Room
            RoomType deluxe = new RoomType();
            deluxe.setTypeName("Deluxe");
            deluxe.setDescription("Spacious deluxe room with premium amenities and city views.");
            deluxe.setBaseRate(new BigDecimal("250.00"));
            deluxe.setDefaultMaxOccupancy(3);
            deluxe.setIncludedAmenities("Wi-Fi, 55\" TV, Mini-bar, Coffee machine, Lounge area, Bathtub");
            roomTypeDAO.addRoomType(deluxe);
            
            // Create Suite
            RoomType suite = new RoomType();
            suite.setTypeName("Suite");
            suite.setDescription("Luxurious suite with separate living room and bedroom areas.");
            suite.setBaseRate(new BigDecimal("400.00"));
            suite.setDefaultMaxOccupancy(4);
            suite.setIncludedAmenities("Wi-Fi, 65\" TV, Full bar, Espresso machine, Living room, Premium bathroom, Work desk");
            roomTypeDAO.addRoomType(suite);
            
            // Create Presidential Suite
            RoomType presidential = new RoomType();
            presidential.setTypeName("Presidential");
            presidential.setDescription("The ultimate luxury experience with unparalleled amenities and service.");
            presidential.setBaseRate(new BigDecimal("850.00"));
            presidential.setDefaultMaxOccupancy(6);
            presidential.setIncludedAmenities("Wi-Fi, Multiple TVs, Full kitchen, Bar, Dining area, Jacuzzi, Butler service");
            roomTypeDAO.addRoomType(presidential);
            
            System.out.println("Default room types added successfully.");
        } else {
            System.out.println("Room types already exist in the database.");
        }
    }

    /**
     * Ensure that services exist in the database
     */
    private static void ensureServicesExist() {
        try {
            com.example.demo10.raffles.hotelmgmt.dao.ServiceDAO serviceDAO = 
                new com.example.demo10.raffles.hotelmgmt.dao.ServiceDAO();
            serviceDAO.ensureDefaultServicesExist();
            System.out.println("Service data initialized.");
        } catch (Exception e) {
            System.err.println("Error initializing services: " + e.getMessage());
            e.printStackTrace();
        }
    }
}