package com.example.demo10.raffles.hotelmgmt.util;

import com.example.demo10.raffles.hotelmgmt.DatabaseConnector;
import com.example.demo10.raffles.hotelmgmt.DatabaseInitializer;

import java.io.File;
import java.sql.Connection;
import java.sql.SQLException;
import java.sql.Statement;

/**
 * Utility class to reset the database in case of corruption
 */
public class DatabaseResetUtil {

    /**
     * Reset the database completely by deleting all database files and recreating them
     * @return true if successful, false otherwise
     */
    public static boolean resetDatabaseCompletely() {
        System.out.println("Attempting to completely reset the database...");
        
        try {
            // First close any existing connections
            DatabaseConnector.closeConnection();
            
            // Delete database files
            String dbFolder = System.getProperty("user.home") + File.separator + "raffles_db";
            File folder = new File(dbFolder);
            
            if (folder.exists() && folder.isDirectory()) {
                File[] files = folder.listFiles();
                if (files != null) {
                    for (File file : files) {
                        if (file.isFile() && file.getName().startsWith("raffleshotel")) {
                            boolean deleted = file.delete();
                            System.out.println("Deleted file " + file.getName() + ": " + deleted);
                        }
                    }
                }
            }
            
            // Reinitialize the database
            DatabaseInitializer.initialize();
            
            System.out.println("Database reset complete!");
            return true;
            
        } catch (Exception e) {
            System.err.println("Error resetting database: " + e.getMessage());
            e.printStackTrace();
            return false;
        }
    }
    
    /**
     * Reset just the Invoice and Charge tables
     * @return true if successful, false otherwise
     */
    public static boolean resetInvoiceTables() {
        System.out.println("Attempting to reset Invoice and Charge tables...");
        
        try (Connection conn = DatabaseConnector.getConnection();
             Statement stmt = conn.createStatement()) {
             
            // Drop tables in correct order to avoid foreign key constraints
            stmt.execute("DROP TABLE IF EXISTS Charge");
            stmt.execute("DROP TABLE IF EXISTS Payment");
            stmt.execute("DROP TABLE IF EXISTS Invoice");
            
            // Recreate Invoice table
            stmt.execute("CREATE TABLE IF NOT EXISTS Invoice (" +
                    "InvoiceID INTEGER GENERATED BY DEFAULT AS IDENTITY(START WITH 1, INCREMENT BY 1) PRIMARY KEY, " +
                    "ReservationID INTEGER, GuestID INTEGER, InvoiceDate DATE DEFAULT CURRENT_DATE, DueDate DATE, " +
                    "TotalAmount DECIMAL(10,2) DEFAULT 0.00, AmountPaid DECIMAL(10,2) DEFAULT 0.00, " +
                    "BalanceDue DECIMAL(10,2) DEFAULT 0.00, " +
                    "Status VARCHAR(50) DEFAULT 'Unpaid', " +
                    "FOREIGN KEY (ReservationID) REFERENCES Reservation(ReservationID) ON DELETE SET NULL, " +
                    "FOREIGN KEY (GuestID) REFERENCES Guest(GuestID) ON DELETE SET NULL)");
            
            // Recreate Charge table
            stmt.execute("CREATE TABLE IF NOT EXISTS Charge (" +
                    "ChargeID INTEGER GENERATED BY DEFAULT AS IDENTITY(START WITH 1, INCREMENT BY 1) PRIMARY KEY, " +
                    "InvoiceID INTEGER NOT NULL, ServiceID INTEGER, Description VARCHAR(255), Amount DECIMAL(10,2) NOT NULL, " +
                    "ChargeDate DATE DEFAULT CURRENT_DATE, ChargedByEmployeeID INTEGER, " +
                    "FOREIGN KEY (InvoiceID) REFERENCES Invoice(InvoiceID) ON DELETE CASCADE, " +
                    "FOREIGN KEY (ServiceID) REFERENCES Service(ServiceID) ON DELETE SET NULL, " +
                    "FOREIGN KEY (ChargedByEmployeeID) REFERENCES Employee(EmployeeID) ON DELETE SET NULL)");
            
            // Recreate Payment table
            stmt.execute("CREATE TABLE IF NOT EXISTS Payment (" +
                    "PaymentID INTEGER GENERATED BY DEFAULT AS IDENTITY(START WITH 1, INCREMENT BY 1) PRIMARY KEY, " +
                    "InvoiceID INTEGER NOT NULL, PaymentDate DATE DEFAULT CURRENT_DATE, AmountPaid DECIMAL(10,2) NOT NULL, " +
                    "PaymentMethod VARCHAR(50), TransactionReference VARCHAR(100), ProcessedByEmployeeID INTEGER, " +
                    "FOREIGN KEY (InvoiceID) REFERENCES Invoice(InvoiceID) ON DELETE CASCADE, " +
                    "FOREIGN KEY (ProcessedByEmployeeID) REFERENCES Employee(EmployeeID) ON DELETE SET NULL)");
            
            System.out.println("Invoice tables reset complete!");
            return true;
            
        } catch (SQLException e) {
            System.err.println("Error resetting invoice tables: " + e.getMessage());
            e.printStackTrace();
            return false;
        }
    }
} 