package com.example.demo10.raffles.hotelmgmt.dao;

import com.example.demo10.raffles.hotelmgmt.DatabaseConnector;
import com.example.demo10.raffles.hotelmgmt.model.GuestAccount;
import javafx.collections.FXCollections;
import javafx.collections.ObservableList;

import java.sql.*;
import java.time.LocalDateTime;
import java.util.Optional;
import java.util.UUID;

public class GuestAccountDAO {

    /**
     * Constructor that automatically initializes the table
     */
    public GuestAccountDAO() {
        // Initialize table when DAO is created
        initTable();
    }

    /**
     * Initialize database table if it doesn't exist
     */
    public void initTable() {
        try (Connection conn = DatabaseConnector.getConnection();
             Statement stmt = conn.createStatement()) {

            // Create GuestAccount table if it doesn't exist
            stmt.execute("CREATE TABLE IF NOT EXISTS GuestAccount (" +
                    "AccountID INTEGER GENERATED BY DEFAULT AS IDENTITY(START WITH 1, INCREMENT BY 1) PRIMARY KEY, " +
                    "Email VARCHAR(100) NOT NULL UNIQUE, " +
                    "Password VARCHAR(255) NOT NULL, " +
                    "GuestID INTEGER NOT NULL, " +
                    "IsActive BOOLEAN DEFAULT TRUE, " +
                    "VerificationCode VARCHAR(50), " +
                    "IsVerified BOOLEAN DEFAULT FALSE, " +
                    "LastLogin TIMESTAMP, " +
                    "CreatedAt TIMESTAMP DEFAULT CURRENT_TIMESTAMP, " +
                    "FOREIGN KEY (GuestID) REFERENCES Guest(GuestID) ON DELETE CASCADE)");
            System.out.println("Checked/Created GuestAccount table.");
        } catch (SQLException e) {
            System.err.println("Error initializing GuestAccount table: " + e.getMessage());
            e.printStackTrace();
        }
    }

    /**
     * Create a new guest account
     */
    public boolean addGuestAccount(GuestAccount account) {
        String verificationCode = UUID.randomUUID().toString().substring(0, 8);
        String sql = "INSERT INTO GuestAccount (Email, Password, GuestID, VerificationCode) VALUES (?, ?, ?, ?)";
        
        try (Connection conn = DatabaseConnector.getConnection();
             PreparedStatement pstmt = conn.prepareStatement(sql, Statement.RETURN_GENERATED_KEYS)) {
            
            pstmt.setString(1, account.getEmail().toLowerCase().trim());
            pstmt.setString(2, account.getPassword());
            pstmt.setInt(3, account.getGuestId());
            pstmt.setString(4, verificationCode);
            
            int affectedRows = pstmt.executeUpdate();
            if (affectedRows > 0) {
                try (ResultSet generatedKeys = pstmt.getGeneratedKeys()) {
                    if (generatedKeys.next()) {
                        account.setAccountId(generatedKeys.getInt(1));
                        account.setVerificationCode(verificationCode);
                        return true;
                    }
                }
            }
            return false;
        } catch (SQLException e) {
            System.err.println("Error adding guest account: " + e.getMessage());
            if (e.getSQLState().equals("23505")) { // Unique violation
                System.err.println("Account with email " + account.getEmail() + " already exists");
            }
            return false;
        }
    }

    /**
     * Find a guest account by email
     */
    public Optional<GuestAccount> findByEmail(String email) {
        String sql = "SELECT * FROM GuestAccount WHERE Email = ?";
        
        try (Connection conn = DatabaseConnector.getConnection();
             PreparedStatement pstmt = conn.prepareStatement(sql)) {
             
            pstmt.setString(1, email.toLowerCase().trim());
            
            try (ResultSet rs = pstmt.executeQuery()) {
                if (rs.next()) {
                    return Optional.of(mapResultSetToGuestAccount(rs));
                }
            }
        } catch (SQLException e) {
            System.err.println("Error finding guest account by email: " + e.getMessage());
        }
        
        return Optional.empty();
    }

    /**
     * Find a guest account by ID
     */
    public Optional<GuestAccount> findById(int accountId) {
        String sql = "SELECT * FROM GuestAccount WHERE AccountID = ?";
        
        try (Connection conn = DatabaseConnector.getConnection();
             PreparedStatement pstmt = conn.prepareStatement(sql)) {
             
            pstmt.setInt(1, accountId);
            
            try (ResultSet rs = pstmt.executeQuery()) {
                if (rs.next()) {
                    return Optional.of(mapResultSetToGuestAccount(rs));
                }
            }
        } catch (SQLException e) {
            System.err.println("Error finding guest account by ID: " + e.getMessage());
        }
        
        return Optional.empty();
    }

    /**
     * Get all guest accounts
     */
    public ObservableList<GuestAccount> getAllAccounts() {
        ObservableList<GuestAccount> accounts = FXCollections.observableArrayList();
        String sql = "SELECT * FROM GuestAccount ORDER BY CreatedAt DESC";
        
        try (Connection conn = DatabaseConnector.getConnection();
             Statement stmt = conn.createStatement();
             ResultSet rs = stmt.executeQuery(sql)) {
             
            while (rs.next()) {
                accounts.add(mapResultSetToGuestAccount(rs));
            }
        } catch (SQLException e) {
            System.err.println("Error getting all guest accounts: " + e.getMessage());
        }
        
        return accounts;
    }

    /**
     * Update an existing guest account
     */
    public boolean updateGuestAccount(GuestAccount account) {
        String sql = "UPDATE GuestAccount SET Email = ?, Password = ?, IsActive = ?, IsVerified = ? WHERE AccountID = ?";
        
        try (Connection conn = DatabaseConnector.getConnection();
             PreparedStatement pstmt = conn.prepareStatement(sql)) {
             
            pstmt.setString(1, account.getEmail().toLowerCase().trim());
            pstmt.setString(2, account.getPassword());
            pstmt.setBoolean(3, account.isActive());
            pstmt.setBoolean(4, account.isVerified());
            pstmt.setInt(5, account.getAccountId());
            
            return pstmt.executeUpdate() > 0;
        } catch (SQLException e) {
            System.err.println("Error updating guest account: " + e.getMessage());
            return false;
        }
    }

    /**
     * Record a login by updating the lastLogin timestamp
     */
    public boolean recordLogin(int accountId) {
        String sql = "UPDATE GuestAccount SET LastLogin = CURRENT_TIMESTAMP WHERE AccountID = ?";
        
        try (Connection conn = DatabaseConnector.getConnection();
             PreparedStatement pstmt = conn.prepareStatement(sql)) {
             
            pstmt.setInt(1, accountId);
            
            return pstmt.executeUpdate() > 0;
        } catch (SQLException e) {
            System.err.println("Error recording login: " + e.getMessage());
            return false;
        }
    }

    /**
     * Check if login credentials are valid
     */
    public Optional<GuestAccount> validateLogin(String email, String password) {
        String sql = "SELECT * FROM GuestAccount WHERE Email = ? AND Password = ? AND IsActive = TRUE";
        
        try (Connection conn = DatabaseConnector.getConnection();
             PreparedStatement pstmt = conn.prepareStatement(sql)) {
             
            pstmt.setString(1, email.toLowerCase().trim());
            pstmt.setString(2, password);
            
            try (ResultSet rs = pstmt.executeQuery()) {
                if (rs.next()) {
                    GuestAccount account = mapResultSetToGuestAccount(rs);
                    recordLogin(account.getAccountId());
                    return Optional.of(account);
                }
            }
        } catch (SQLException e) {
            System.err.println("Error validating login: " + e.getMessage());
        }
        
        return Optional.empty();
    }

    /**
     * Map ResultSet row to GuestAccount object
     */
    private GuestAccount mapResultSetToGuestAccount(ResultSet rs) throws SQLException {
        GuestAccount account = new GuestAccount();
        account.setAccountId(rs.getInt("AccountID"));
        account.setEmail(rs.getString("Email"));
        account.setPassword(rs.getString("Password"));
        account.setGuestId(rs.getInt("GuestID"));
        account.setActive(rs.getBoolean("IsActive"));
        account.setVerificationCode(rs.getString("VerificationCode"));
        account.setVerified(rs.getBoolean("IsVerified"));
        
        Timestamp lastLoginTs = rs.getTimestamp("LastLogin");
        if (lastLoginTs != null) {
            account.setLastLogin(lastLoginTs.toLocalDateTime());
        }
        
        Timestamp createdAtTs = rs.getTimestamp("CreatedAt");
        if (createdAtTs != null) {
            account.setCreatedAt(createdAtTs.toLocalDateTime());
        }
        
        return account;
    }
} 